branch-defaults:
  main:
    environment: my-env-jetcart
    group_suffix: null
environment-defaults:
  jetstoz-course-env:
    branch: null
    repository: null
global:
  application_name: jetcart-course-online
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
